# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-08 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nk', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nk', models.CharField(help_text=b'e.g. {recipe.nk}$${food.nk}', max_length=255, unique=True)),
                ('desc', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('rank', models.IntegerField(default=0)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.Food')),
            ],
            options={
                'default_related_name': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nk', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[(b'QUANTITY', b'QUANTITY'), (b'WEIGHT', b'WEIGHT'), (b'VOLUME', b'VOLUME')], max_length=255)),
                ('unit', models.CharField(choices=[(b'TEASPOON', b'TEASPOON'), (b'TABLESPOON', b'TABLESPOON'), (b'CUP', b'CUP'), (b'PINT', b'PINT'), (b'QUART', b'QUART'), (b'GALLON', b'GALLON'), (b'OUNCE', b'OUNCE'), (b'POUND', b'POUND')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nk', models.CharField(max_length=255, unique=True)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6)),
                ('volume', models.DecimalField(decimal_places=3, max_digits=6)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.Food')),
                ('volume_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_measurement_conversions', to='foodie.Measurement')),
                ('weight_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_measurement_conversions', to='foodie.Measurement')),
            ],
            options={
                'default_related_name': 'measurement_conversions',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nk', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=6)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.Food')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.Measurement')),
            ],
            options={
                'default_related_name': 'products',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nk', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodie.Measurement'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.Recipe'),
        ),
    ]
