# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-27 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import foodie.models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nk', foodie.models.NKField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            bases=(models.Model, foodie.models.NKMixin),
        ),
        migrations.CreateModel(
            name='FoodXAllergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nk', foodie.models.NKField(help_text=b'e.g. {food.nk}$${allergen.nk}', max_length=255, unique=True)),
                ('rank', models.IntegerField(default=0, help_text=b'Controls the display order in the UI.')),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.Allergen')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.Food')),
            ],
            bases=(models.Model, foodie.models.NKMixin),
        ),
    ]
