# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-28 05:47
from __future__ import unicode_literals

from django.db import migrations
import foodie.models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0002_allergen_foodxallergen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='nk',
            field=foodie.models.NKField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='nk',
            field=foodie.models.NKField(help_text=b'e.g. {recipe.nk}$${food.nk}', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='nk',
            field=foodie.models.NKField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='measurementconversion',
            name='nk',
            field=foodie.models.NKField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nk',
            field=foodie.models.NKField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nk',
            field=foodie.models.NKField(max_length=255, unique=True),
        ),
    ]
